services:
  - type: web
    name: interarcade-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python secret.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"

  - type: worker
    name: interarcade-listener
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python tiktok_listener.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
